/*
 * @copyright Copyright (c) 2010 Laboratório de Educação Cerebral. (http://www.educacaocerebral.com.br)
 *
 * This file is part of SoftVFC.
 *
 * SoftVFC is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SoftVFC is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SoftVFC.  If not, see <http://www.gnu.org/licenses/>.
 *
 * *********************
 *
 * Este arquivo é parte do programa SoftVFC.
 *
 * SoftVFC é um software livre; você pode redistribui-lo e/ou
 * modifica-lo dentro dos termos da Licença Pública Geral GNU como
 * publicada pela Fundação do Software Livre (FSF); na versão 3 da
 * Licença.
 *
 * Este programa é distribuido na esperança que possa ser util,
 * mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
 * MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU para maiores detalhes.
 *
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU
 * junto com este programa, se não, acesse no website oficial:
 * http://www.gnu.org/licenses/gpl.html
 *
 */
/**
 *
 * @author Diego Schmaedech Martins (schmaedech@gmail.com)
 * @version 29/07/2010
 */

package com.sdk.connector.db;

import javax.swing.event.EventListenerList;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author  John O'Conner
 */
public class AquisitionActionPanel extends javax.swing.JPanel  {
    
    /**
     * Creates new form AquisitionActionPanel
     */
    public AquisitionActionPanel() {
        initComponents();
        listeners = new EventListenerList();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewAddress = new javax.swing.JButton();
        btnDeleteAddress = new javax.swing.JButton();
        btnEditAddress = new javax.swing.JButton();
        btnSaveAddress = new javax.swing.JButton();
        btnCancelAddress = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 0));

        btnNewAddress.setText("New");
        btnNewAddress.setActionCommand("NEW_AQUISITION");
        btnNewAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAddressActionPerformed(evt);
            }
        });
        add(btnNewAddress);

        btnDeleteAddress.setText("Delete");
        btnDeleteAddress.setActionCommand("DELETE_AQUISITION");
        btnDeleteAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAddressActionPerformed(evt);
            }
        });
        add(btnDeleteAddress);

        btnEditAddress.setText("Edit");
        btnEditAddress.setActionCommand("EDIT_AQUISITION");
        btnEditAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAddressActionPerformed(evt);
            }
        });
        add(btnEditAddress);

        btnSaveAddress.setText("Save");
        btnSaveAddress.setActionCommand("SAVE_AQUISITION");
        btnSaveAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAddressActionPerformed(evt);
            }
        });
        add(btnSaveAddress);

        btnCancelAddress.setText("Cancel");
        btnCancelAddress.setActionCommand("CANCEL_AQUISITION");
        btnCancelAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddressActionPerformed(evt);
            }
        });
        add(btnCancelAddress);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddressActionPerformed
        fireActionEvent(evt);
    }//GEN-LAST:event_cancelAddressActionPerformed

    private void saveAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAddressActionPerformed
        fireActionEvent(evt);
    }//GEN-LAST:event_saveAddressActionPerformed

    private void editAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAddressActionPerformed
        fireActionEvent(evt);
    }//GEN-LAST:event_editAddressActionPerformed

    private void deleteAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAddressActionPerformed
        fireActionEvent(evt);
    }//GEN-LAST:event_deleteAddressActionPerformed

    private void newAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAddressActionPerformed
        fireActionEvent(evt);
    }//GEN-LAST:event_newAddressActionPerformed

    private void fireActionEvent(ActionEvent evt) {
        ActionListener[] listenerList = listeners.getListeners(ActionListener.class);

        for (int i = listenerList.length-1; i>=0; --i) {
            listenerList[i].actionPerformed(evt);
        }
        
    }
    
    public void addActionListener(ActionListener listener) {
        listeners.add(ActionListener.class, listener);
    }
    
    public void removeActionListener(ActionListener listener) {
        if (listeners != null) {
            listeners.remove(ActionListener.class, listener);
        }
    }
    
    EventListenerList listeners;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelAddress;
    private javax.swing.JButton btnDeleteAddress;
    private javax.swing.JButton btnEditAddress;
    private javax.swing.JButton btnNewAddress;
    private javax.swing.JButton btnSaveAddress;
    // End of variables declaration//GEN-END:variables
    
}
