/*
 * @copyright Copyright (c) 2010 Laboratório de Educação Cerebral. (http://www.educacaocerebral.com.br)
 *
 * This file is part of SoftVFC.
 *
 * SoftVFC is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SoftVFC is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SoftVFC.  If not, see <http://www.gnu.org/licenses/>.
 *
 * *********************
 *
 * Este arquivo é parte do programa SoftVFC.
 *
 * SoftVFC é um software livre; você pode redistribui-lo e/ou
 * modifica-lo dentro dos termos da Licença Pública Geral GNU como
 * publicada pela Fundação do Software Livre (FSF); na versão 3 da
 * Licença.
 *
 * Este programa é distribuido na esperança que possa ser util,
 * mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
 * MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU para maiores detalhes.
 *
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU
 * junto com este programa, se não, acesse no website oficial:
 * http://www.gnu.org/licenses/gpl.html
 *
 */
/**
 *
 * @author Diego Schmaedech Martins (schmaedech@gmail.com)
 * @version 29/07/2010
 */

package com.sdk.connector.settings;



/**
 *
 * @author diego
 */
public class RRBCSettingsPanel extends javax.swing.JPanel {

    private static RRBCSettingsEntity rrbcSettingsEntity = new RRBCSettingsEntity();

    /**
     * @return the fftSettingsEntity
     */
    public static RRBCSettingsEntity getRRBCSettingsEntity() {
        return rrbcSettingsEntity;
    }
    /** Creates new form CoerenceSettingsPanel */
    public RRBCSettingsPanel() {
        initComponents();
        setEditable(false);
        updateFields();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtfPlotPoints = new javax.swing.JTextField();
        jlAprox = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jbEdit = new javax.swing.JButton();
        jbUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Output", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("DejaVu Sans", 1, 10))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(540, 390));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/sdk/connector/settings/Bundle"); // NOI18N
        jLabel6.setText(bundle.getString("PLOT POINTS:")); // NOI18N
        jPanel9.add(jLabel6);

        jtfPlotPoints.setColumns(5);
        jtfPlotPoints.setText("256");
        jPanel9.add(jtfPlotPoints);

        jlAprox.setFont(new java.awt.Font("DejaVu Sans", 2, 10));
        jlAprox.setText(bundle.getString("APROX. 4 MIN.")); // NOI18N
        jPanel9.add(jlAprox);

        jPanel2.add(jPanel9);

        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(540, 37));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jbEdit.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jbEdit.setText(bundle.getString("EDIT")); // NOI18N
        jbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditActionPerformed(evt);
            }
        });
        jPanel11.add(jbEdit);

        jbUpdate.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jbUpdate.setText(bundle.getString("UPDATE")); // NOI18N
        jbUpdate.setEnabled(false);
        jbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateActionPerformed(evt);
            }
        });
        jPanel11.add(jbUpdate);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditActionPerformed
        setEditable(true);
        jbUpdate.setEnabled(true);
        jbEdit.setEnabled(false);
        repaint();
}//GEN-LAST:event_jbEditActionPerformed

    private void jbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateActionPerformed
        updateFields();
        jbUpdate.setEnabled(false);
        jbEdit.setEnabled(true);
        setEditable(false);
}//GEN-LAST:event_jbUpdateActionPerformed

    private void updateFields(){
        getRRBCSettingsEntity().setPlotPoints(Integer.parseInt(jtfPlotPoints.getText()));
        jlAprox.setText(java.util.ResourceBundle.getBundle("com/sdk/connector/settings/Bundle").getString("APROX. ")+String.valueOf(getRRBCSettingsEntity().getPlotPoints() / 60) + " min. ");
    }

    private void setEditable(boolean flag){
        jLabel6.setEnabled(flag);
        jPanel11.setEnabled(flag);
        jPanel2.setEnabled(flag);
        jtfPlotPoints.setEnabled(flag);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbEdit;
    private javax.swing.JButton jbUpdate;
    private javax.swing.JLabel jlAprox;
    private javax.swing.JTextField jtfPlotPoints;
    // End of variables declaration//GEN-END:variables

}
